# Generated by Django 2.2 on 2019-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindeck',
            name='in_sideboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
