# Generated by Django 2.1.7 on 2019-02-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190220_2153'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardsInDeck',
            new_name='CardInDeck',
        ),
        migrations.AddField(
            model_name='deck',
            name='card_in_deck',
            field=models.ManyToManyField(through='decks.CardInDeck', to='cards.Edition'),
        ),
    ]
