# Generated by Django 2.1.7 on 2019-02-21 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rules_text', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('cost', models.CharField(max_length=50)),
                ('cmc', models.IntegerField()),
                ('loyalty', models.CharField(max_length=10)),
                ('type_line', models.CharField(max_length=200)),
                ('reserved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('number', models.CharField(max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('flavor_text', models.TextField(blank=True)),
                ('multiverse_id', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField(blank=True)),
                ('promo_release_date', models.CharField(blank=True, max_length=20)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Artist')),
                ('border', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Border')),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Block')),
            ],
        ),
        migrations.CreateModel(
            name='FlipCardPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_side_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_side_card_name', to='cards.CardName')),
                ('night_side_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='night_side_card_name', to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_name', models.CharField(max_length=400)),
                ('multiverse_id', models.IntegerField(blank=True, null=True)),
                ('rules_text', models.TextField(blank=True)),
                ('flavor_text', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Legality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Format')),
            ],
        ),
        migrations.CreateModel(
            name='LegalityType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeldCardTriplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottom_card_name', to='cards.CardName')),
                ('meld_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meld_card_name', to='cards.CardName')),
                ('top_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_card_name', to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='SplitCardPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_side_card_name', to='cards.CardName')),
                ('right_side_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_side_card_name', to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supertype',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='legality',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.LegalityType'),
        ),
        migrations.AddField(
            model_name='foreignversion',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Language'),
        ),
        migrations.AddField(
            model_name='edition',
            name='expansion_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Expansion'),
        ),
        migrations.AddField(
            model_name='edition',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Rarity'),
        ),
        migrations.AddField(
            model_name='edition',
            name='watermark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Watermark'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color_colors', to='cards.Color'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='color_identity',
            field=models.ManyToManyField(blank=True, related_name='color_identity_colors', to='cards.Color'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Layout'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='cards.Subtype'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='supertype',
            field=models.ManyToManyField(blank=True, to='cards.Supertype'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='type',
            field=models.ManyToManyField(to='cards.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='splitcardpair',
            unique_together={('left_side_card', 'right_side_card')},
        ),
        migrations.AlterUniqueTogether(
            name='ruling',
            unique_together={('card_name', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='meldcardtriplet',
            unique_together={('top_card', 'bottom_card', 'meld_card')},
        ),
        migrations.AlterUniqueTogether(
            name='legality',
            unique_together={('card_name', 'format')},
        ),
        migrations.AlterUniqueTogether(
            name='foreignversion',
            unique_together={('edition', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='flipcardpair',
            unique_together={('day_side_card', 'night_side_card')},
        ),
    ]
