# Generated by Django 2.1 on 2018-12-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardLegality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rules_text', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('cost', models.CharField(max_length=50)),
                ('cmc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_text', models.TextField(blank=True)),
                ('multiverse_id', models.IntegerField()),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName')),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LegalityType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ManyToManyField(to='cards.Type'),
        ),
        migrations.AddField(
            model_name='edition',
            name='expansion_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Expansion'),
        ),
        migrations.AddField(
            model_name='edition',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Rarity'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='color',
            field=models.ManyToManyField(blank=True, to='cards.Color'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='cards.SubType'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='type',
            field=models.ManyToManyField(to='cards.Type'),
        ),
        migrations.AddField(
            model_name='cardlegality',
            name='card_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='cardlegality',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Format'),
        ),
        migrations.AddField(
            model_name='cardlegality',
            name='legality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.LegalityType'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('card_name', 'expansion_name')},
        ),
        migrations.AlterUniqueTogether(
            name='cardlegality',
            unique_together={('card_name', 'format')},
        ),
    ]
