# Generated by Django 2.1.5 on 2019-01-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlipCardPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_name', models.CharField(max_length=400)),
                ('multiverse_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeldCardTriplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CardLegality',
            new_name='LegalityExceptions',
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='type',
        ),
        migrations.AddField(
            model_name='cardname',
            name='color_identity',
            field=models.ManyToManyField(blank=True, related_name='color_identity_colors', to='cards.Color'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='loyalty',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardname',
            name='reserved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardname',
            name='type_line',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='promo_release_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='edition',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color_colors', to='cards.Color'),
        ),
        migrations.AddField(
            model_name='edition',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cards.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='border',
            field=models.ForeignKey(default='Black', on_delete=django.db.models.deletion.PROTECT, to='cards.Border'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='watermark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Watermark'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('card_name', 'expansion_name', 'number')},
        ),
        migrations.AddField(
            model_name='ruling',
            name='card_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='meldcardtriplet',
            name='bottom_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottom_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='meldcardtriplet',
            name='meld_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meld_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='meldcardtriplet',
            name='top_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='foreignname',
            name='english_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='foreignname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Language'),
        ),
        migrations.AddField(
            model_name='flipcardpair',
            name='day_side_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_side_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='flipcardpair',
            name='night_side_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='night_side_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='cardname',
            name='layout',
            field=models.ForeignKey(default='Normal', on_delete=django.db.models.deletion.PROTECT, to='cards.Layout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardname',
            name='supertype',
            field=models.ManyToManyField(blank=True, to='cards.SuperType'),
        ),
    ]
