# Generated by Django 2.1.7 on 2019-03-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190223_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_expansion', to='cards.Expansion'),
        ),
    ]
