# Generated by Django 2.1.7 on 2019-02-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190110_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_name', models.CharField(max_length=400)),
                ('multiverse_id', models.IntegerField(blank=True, null=True)),
                ('rules_text', models.TextField(blank=True)),
                ('flavor_text', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SplitCardPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='LegalityExceptions',
            new_name='Legality',
        ),
        migrations.RemoveField(
            model_name='foreignname',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='foreignname',
            name='language',
        ),
        migrations.RenameField(
            model_name='legality',
            old_name='legality',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='cardname',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='color_colors', to='cards.Color'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='color_identity',
            field=models.ManyToManyField(blank=True, null=True, related_name='color_identity_colors', to='cards.Color'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='subtype',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Subtype'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='supertype',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Supertype'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='edition',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='edition',
            name='multiverse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='block',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cards.Block'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='flipcardpair',
            unique_together={('day_side_card', 'night_side_card')},
        ),
        migrations.AlterUniqueTogether(
            name='meldcardtriplet',
            unique_together={('top_card', 'bottom_card', 'meld_card')},
        ),
        migrations.AlterUniqueTogether(
            name='ruling',
            unique_together={('card_name', 'text')},
        ),
        migrations.DeleteModel(
            name='ForeignName',
        ),
        migrations.AddField(
            model_name='splitcardpair',
            name='left_side_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_side_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='splitcardpair',
            name='right_side_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_side_card_name', to='cards.CardName'),
        ),
        migrations.AddField(
            model_name='foreignversion',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Edition'),
        ),
        migrations.AddField(
            model_name='foreignversion',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='splitcardpair',
            unique_together={('left_side_card', 'right_side_card')},
        ),
        migrations.AlterUniqueTogether(
            name='foreignversion',
            unique_together={('edition', 'language')},
        ),
    ]
