# Generated by Django 2.1.7 on 2019-03-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_expansion_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foreignversion',
            unique_together=set(),
        ),
    ]
