# Generated by Django 2.1.7 on 2019-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190220_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardname',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color_colors', to='cards.Color'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='color_identity',
            field=models.ManyToManyField(blank=True, related_name='color_identity_colors', to='cards.Color'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='cards.Subtype'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='supertype',
            field=models.ManyToManyField(blank=True, to='cards.Supertype'),
        ),
    ]
