# Generated by Django 2.1.7 on 2019-02-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190220_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardname',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='cards.Subtype'),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='supertype',
            field=models.ManyToManyField(blank=True, to='cards.Supertype'),
        ),
    ]
