# Generated by Django 2.1.7 on 2019-03-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190307_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruling',
            unique_together=set(),
        ),
    ]
