# Generated by Django 2.2 on 2019-04-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190307_0054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruling',
            unique_together={('card_name', 'date', 'text')},
        ),
    ]
